### ISSUE TITLE
数据设置错误！

### ISSUE THREAD

**Issue by fengtalk** [bestony/pay-to-view-all#13]
设置页面截图如下：
![default](https://user-images.githubusercontent.com/2913058/35554902-47c5f4fe-05d8-11e8-8ff5-f782fe350d34.png)

打开文章页面，登录之后，自动跳转到/wp-admin/profile.php页面。

再次打开文章页面，提示“数据设置错误！”

**Comment by fengtalk** [comment]
测试页面：http://wp.fengtalk.com/1.html
PayJS的后台会产生“用户订单号”。

**Comment by bestony** [comment]
已经定位到相关的代码，有个问题想咨询一下。

是否是支付过后刷新页面的？

此外，能否提供文章页面中自定义栏目的截图，比如这样

![xnip2018-01-30_16-41-42](https://user-images.githubusercontent.com/13283837/35556176-89f8418e-05dc-11e8-90d2-69ef68e3b4ff.jpg)

可以在页面右上角的 「自定义栏目」看到。

**Comment by fengtalk** [comment]
没出现要扫描的二维码，所以是没有扫码支付。自定义栏目截图如下：
![bug-fb](https://user-images.githubusercontent.com/2913058/35574638-4bc8d174-0615-11e8-9035-51b7f05d27cb.jpg)

**Comment by bestony** [comment]
好的，感谢，我看一下问题所在。

**Comment by bestony** [comment]
@fengtalk 这个问题已经修复了，你试试下载最新版的代码。
