### ISSUE TITLE
打开文章页特别慢，打开之后是空白

### ISSUE THREAD

**Issue by fengtalk** [bestony/pay-to-view-all#15]
http://wp.fengtalk.com/197.html
打开文章页特别慢，打开之后是空白。
只安装了本插件。
测试用户账户和密码分别是demo和demo123...

**Comment by bestony** [comment]
你的服务端环境是什么？是最新版的代码么？可以试试打开 wordpress 的 debug 来查看报错。

**Comment by xhat** [comment]
禁用插件还有此问题么

**Comment by fengtalk** [comment]
@bestony 
服务器环境如下：
Ubuntu 16.04.3
nginx 1.12.1
MySQL 5.6.33
PHP 5.6.26
插件是最新版本的。我打开 wordpress 的 debug 看看。

@xhat 禁用插件之后，页面正常显示。

**Comment by xhat** [comment]
大概知道原因了。插件中body名称过长导致获取不到二维码 @bestony

**Comment by fengtalk** [comment]
插件设置页面的报错信息如下：
Notice: Undefined index: pay_to_view_all_field in /data/wwwroot/wp.fengtalk.com/wp-content/plugins/pay-to-view-all-master/pay-to-view-all.php on line 56
![notice](https://user-images.githubusercontent.com/2913058/35636563-804b8108-06ec-11e8-8bfa-e9c3339997a5.jpg)

@bestony

**Comment by bestony** [comment]
好的，收到。我调试一下，应该和 WordPress 本身的API有关？
@fengtalk 你设置的自定义前缀是什么？

**Comment by bestony** [comment]
@fengtalk 刚刚上传了一个新的版本，你测试一下这个版本对你是否可用？

 我又看了一下 API，因为对 body 的长度限制为32，你的文章标题可能太长了。改为使用ID来作为标题了。

**Comment by fengtalk** [comment]
前缀是test。
更新插件，问题解决。
Debug下页面还有点问题，我关闭试试。
@bestony 辛苦了。

**Comment by bestony** [comment]
debug 那个可以不用管，那个是一个校验的。我这几天要研究一下 WP的校验机制。
